-- File generated by bch.exe program.
-- The constant package for BCH code (127,113), t=2
 -- with optimization= 1.
-- GF(2^7) is generated by polynomial [1+x+...] - 11000001;
-- Constant necessary for decoder and encoder

PACKAGE   const IS
	CONSTANT m: INTEGER:= 7;
	CONSTANT n: INTEGER:= 127;  -- n= 2^m -1  -size of block
	CONSTANT k: INTEGER:= 113;  -- BCH code (n,k) -no. of information bits
	CONSTANT nk: INTEGER:= 14; -- nk=n-k
	CONSTANT t: INTEGER:= 2;  -- no. of errors to be corrected

	CONSTANT sizea: INTEGER:= 4; -- size of counter ca
	CONSTANT sizeb: INTEGER:= 4; -- size of counter cb 
		-- count = iteration* cb + ca
	CONSTANT sizel: INTEGER:= 3; 
		-- size of l integer (degree of error polynomial BMA)
END const;	

