-- File generated by bch.exe program.
-- The constant package for BCH code (511,502), t=1

-- GF(2^9) is generated by polynomial [1+x+...] - 1000100001;
-- Constant necessary for decoder and encoder

PACKAGE   const IS
	CONSTANT m: INTEGER:= 9;
	CONSTANT n: INTEGER:= 511;  -- n= 2^m -1  -size of block
	CONSTANT k: INTEGER:= 502;  -- BCH code (n,k) -no. of information bits
	CONSTANT nk: INTEGER:= 9; -- nk=n-k
	CONSTANT t: INTEGER:= 1;  -- no. of errors to be corrected

	CONSTANT sizea: INTEGER:= 2; -- size of counter ca
	CONSTANT sizeb: INTEGER:= 8; -- size of counter cb 
		-- count = iteration* cb + ca
	CONSTANT sizel: INTEGER:= 3; 
		-- size of l integer (degree of error polynomial BMA)
END const;	

