-- File generated by bch.exe program.
-- The constant package for BCH code (63,57), t=1

-- GF(2^6) is generated by polynomial [1+x+...] - 1100001;
-- Constant necessary for decoder and encoder

PACKAGE   const IS
	CONSTANT m: INTEGER:= 6;
	CONSTANT n: INTEGER:= 63;  -- n= 2^m -1  -size of block
	CONSTANT k: INTEGER:= 57;  -- BCH code (n,k) -no. of information bits
	CONSTANT nk: INTEGER:= 6; -- nk=n-k
	CONSTANT t: INTEGER:= 1;  -- no. of errors to be corrected

	CONSTANT sizea: INTEGER:= 3; -- size of counter ca
	CONSTANT sizeb: INTEGER:= 3; -- size of counter cb 
		-- count = iteration* cb + ca
	CONSTANT sizel: INTEGER:= 3; 
		-- size of l integer (degree of error polynomial BMA)
END const;	

